version: '3'
services:
  prepare_app:
    container_name: prepare_app
    image: ambientum/php:7.4-nginx
    volumes:
      - .:/var/www/app
    entrypoint: ./prepareapp.sh
  app:
    container_name: app
    image: ambientum/php:7.4-nginx
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/app
